services:
  - type: web
    name: blast-jira-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run api
    envVars:
      - key: GROQ_KEY
        sync: false
      - key: JIRA_EMAIL
        sync: false
      - key: JIRA_TOKEN
        sync: false
      - key: JIRA_BASE_URL
        sync: false
      - key: PORT
        value: "5174"
